/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompanyRouteImport } from './routes/_company'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySegurosRouteImport } from './routes/_company/seguros'
import { Route as CompanyPerfilRouteImport } from './routes/_company/perfil'
import { Route as CompanyPagosRouteImport } from './routes/_company/pagos'
import { Route as CompanyMovimientosRouteImport } from './routes/_company/movimientos'
import { Route as CompanyEmpleadosRouteImport } from './routes/_company/empleados'
import { Route as CompanyDocumentosRouteImport } from './routes/_company/documentos'
import { Route as ClientMisPolizasRouteImport } from './routes/_client/mis-polizas'
import { Route as ClientMisPagosRouteImport } from './routes/_client/mis-pagos'
import { Route as ClientMisDocumentosRouteImport } from './routes/_client/mis-documentos'
import { Route as ClientMiPerfilRouteImport } from './routes/_client/mi-perfil'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminCarteraRouteImport } from './routes/_admin/cartera'
import { Route as AdminAseguradorasRouteImport } from './routes/_admin/aseguradoras'
import { Route as CompanySegurosPolizaIdRouteImport } from './routes/_company/seguros.$polizaId'
import { Route as CompanyEmpleadoEmpleadoIdRouteImport } from './routes/_company/empleado.$empleadoId'
import { Route as ClientConsentimientoVerRouteImport } from './routes/_client/consentimiento.ver'
import { Route as AdminEmpresaNuevaRouteImport } from './routes/_admin/empresa.nueva'
import { Route as AdminClienteClienteIdRouteImport } from './routes/_admin/cliente.$clienteId'
import { Route as AdminAseguradoraAseguradoraIdRouteImport } from './routes/_admin/aseguradora.$aseguradoraId'
import { Route as ApiPublicAseguradosZipRouteImport } from './routes/api/public/asegurados.zip'
import { Route as ApiPublicAseguradosPdfSplitRouteImport } from './routes/api/public/asegurados.pdf-split'
import { Route as AdminEmpresaPolizaNuevaRouteImport } from './routes/_admin/empresa.poliza.nueva'
import { Route as AdminEmpresaPolizaPolizaIdRouteImport } from './routes/_admin/empresa.poliza.$polizaId'
import { Route as AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRouteImport } from './routes/_admin/empresa.$empresaId.empleado.$empleadoId'
import { Route as AdminClienteClienteIdPolizaPolizaIdRouteImport } from './routes/_admin/cliente.$clienteId.poliza.$polizaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/_company',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySegurosRoute = CompanySegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyPerfilRoute = CompanyPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyPagosRoute = CompanyPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyMovimientosRoute = CompanyMovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyEmpleadosRoute = CompanyEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyDocumentosRoute = CompanyDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => CompanyRoute,
} as any)
const ClientMisPolizasRoute = ClientMisPolizasRouteImport.update({
  id: '/mis-polizas',
  path: '/mis-polizas',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMisPagosRoute = ClientMisPagosRouteImport.update({
  id: '/mis-pagos',
  path: '/mis-pagos',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMisDocumentosRoute = ClientMisDocumentosRouteImport.update({
  id: '/mis-documentos',
  path: '/mis-documentos',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMiPerfilRoute = ClientMiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => ClientRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarteraRoute = AdminCarteraRouteImport.update({
  id: '/cartera',
  path: '/cartera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAseguradorasRoute = AdminAseguradorasRouteImport.update({
  id: '/aseguradoras',
  path: '/aseguradoras',
  getParentRoute: () => AdminRoute,
} as any)
const CompanySegurosPolizaIdRoute = CompanySegurosPolizaIdRouteImport.update({
  id: '/$polizaId',
  path: '/$polizaId',
  getParentRoute: () => CompanySegurosRoute,
} as any)
const CompanyEmpleadoEmpleadoIdRoute =
  CompanyEmpleadoEmpleadoIdRouteImport.update({
    id: '/empleado/$empleadoId',
    path: '/empleado/$empleadoId',
    getParentRoute: () => CompanyRoute,
  } as any)
const ClientConsentimientoVerRoute = ClientConsentimientoVerRouteImport.update({
  id: '/consentimiento/ver',
  path: '/consentimiento/ver',
  getParentRoute: () => ClientRoute,
} as any)
const AdminEmpresaNuevaRoute = AdminEmpresaNuevaRouteImport.update({
  id: '/empresa/nueva',
  path: '/empresa/nueva',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClienteClienteIdRoute = AdminClienteClienteIdRouteImport.update({
  id: '/cliente/$clienteId',
  path: '/cliente/$clienteId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAseguradoraAseguradoraIdRoute =
  AdminAseguradoraAseguradoraIdRouteImport.update({
    id: '/aseguradora/$aseguradoraId',
    path: '/aseguradora/$aseguradoraId',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiPublicAseguradosZipRoute = ApiPublicAseguradosZipRouteImport.update({
  id: '/api/public/asegurados/zip',
  path: '/api/public/asegurados/zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAseguradosPdfSplitRoute =
  ApiPublicAseguradosPdfSplitRouteImport.update({
    id: '/api/public/asegurados/pdf-split',
    path: '/api/public/asegurados/pdf-split',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEmpresaPolizaNuevaRoute = AdminEmpresaPolizaNuevaRouteImport.update({
  id: '/empresa/poliza/nueva',
  path: '/empresa/poliza/nueva',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresaPolizaPolizaIdRoute =
  AdminEmpresaPolizaPolizaIdRouteImport.update({
    id: '/empresa/poliza/$polizaId',
    path: '/empresa/poliza/$polizaId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute =
  AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRouteImport.update({
    id: '/empresa/$empresaId/empleado/$empleadoId',
    path: '/empresa/$empresaId/empleado/$empleadoId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClienteClienteIdPolizaPolizaIdRoute =
  AdminClienteClienteIdPolizaPolizaIdRouteImport.update({
    id: '/poliza/$polizaId',
    path: '/poliza/$polizaId',
    getParentRoute: () => AdminClienteClienteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aseguradoras': typeof AdminAseguradorasRoute
  '/cartera': typeof AdminCarteraRoute
  '/dashboard': typeof AdminDashboardRoute
  '/mi-perfil': typeof ClientMiPerfilRoute
  '/mis-documentos': typeof ClientMisDocumentosRoute
  '/mis-pagos': typeof ClientMisPagosRoute
  '/mis-polizas': typeof ClientMisPolizasRoute
  '/documentos': typeof CompanyDocumentosRoute
  '/empleados': typeof CompanyEmpleadosRoute
  '/movimientos': typeof CompanyMovimientosRoute
  '/pagos': typeof CompanyPagosRoute
  '/perfil': typeof CompanyPerfilRoute
  '/seguros': typeof CompanySegurosRouteWithChildren
  '/aseguradora/$aseguradoraId': typeof AdminAseguradoraAseguradoraIdRoute
  '/cliente/$clienteId': typeof AdminClienteClienteIdRouteWithChildren
  '/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/consentimiento/ver': typeof ClientConsentimientoVerRoute
  '/empleado/$empleadoId': typeof CompanyEmpleadoEmpleadoIdRoute
  '/seguros/$polizaId': typeof CompanySegurosPolizaIdRoute
  '/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
  '/api/public/asegurados/pdf-split': typeof ApiPublicAseguradosPdfSplitRoute
  '/api/public/asegurados/zip': typeof ApiPublicAseguradosZipRoute
  '/cliente/$clienteId/poliza/$polizaId': typeof AdminClienteClienteIdPolizaPolizaIdRoute
  '/empresa/$empresaId/empleado/$empleadoId': typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aseguradoras': typeof AdminAseguradorasRoute
  '/cartera': typeof AdminCarteraRoute
  '/dashboard': typeof AdminDashboardRoute
  '/mi-perfil': typeof ClientMiPerfilRoute
  '/mis-documentos': typeof ClientMisDocumentosRoute
  '/mis-pagos': typeof ClientMisPagosRoute
  '/mis-polizas': typeof ClientMisPolizasRoute
  '/documentos': typeof CompanyDocumentosRoute
  '/empleados': typeof CompanyEmpleadosRoute
  '/movimientos': typeof CompanyMovimientosRoute
  '/pagos': typeof CompanyPagosRoute
  '/perfil': typeof CompanyPerfilRoute
  '/seguros': typeof CompanySegurosRouteWithChildren
  '/aseguradora/$aseguradoraId': typeof AdminAseguradoraAseguradoraIdRoute
  '/cliente/$clienteId': typeof AdminClienteClienteIdRouteWithChildren
  '/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/consentimiento/ver': typeof ClientConsentimientoVerRoute
  '/empleado/$empleadoId': typeof CompanyEmpleadoEmpleadoIdRoute
  '/seguros/$polizaId': typeof CompanySegurosPolizaIdRoute
  '/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
  '/api/public/asegurados/pdf-split': typeof ApiPublicAseguradosPdfSplitRoute
  '/api/public/asegurados/zip': typeof ApiPublicAseguradosZipRoute
  '/cliente/$clienteId/poliza/$polizaId': typeof AdminClienteClienteIdPolizaPolizaIdRoute
  '/empresa/$empresaId/empleado/$empleadoId': typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_client': typeof ClientRouteWithChildren
  '/_company': typeof CompanyRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/aseguradoras': typeof AdminAseguradorasRoute
  '/_admin/cartera': typeof AdminCarteraRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_client/mi-perfil': typeof ClientMiPerfilRoute
  '/_client/mis-documentos': typeof ClientMisDocumentosRoute
  '/_client/mis-pagos': typeof ClientMisPagosRoute
  '/_client/mis-polizas': typeof ClientMisPolizasRoute
  '/_company/documentos': typeof CompanyDocumentosRoute
  '/_company/empleados': typeof CompanyEmpleadosRoute
  '/_company/movimientos': typeof CompanyMovimientosRoute
  '/_company/pagos': typeof CompanyPagosRoute
  '/_company/perfil': typeof CompanyPerfilRoute
  '/_company/seguros': typeof CompanySegurosRouteWithChildren
  '/_admin/aseguradora/$aseguradoraId': typeof AdminAseguradoraAseguradoraIdRoute
  '/_admin/cliente/$clienteId': typeof AdminClienteClienteIdRouteWithChildren
  '/_admin/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/_client/consentimiento/ver': typeof ClientConsentimientoVerRoute
  '/_company/empleado/$empleadoId': typeof CompanyEmpleadoEmpleadoIdRoute
  '/_company/seguros/$polizaId': typeof CompanySegurosPolizaIdRoute
  '/_admin/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/_admin/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
  '/api/public/asegurados/pdf-split': typeof ApiPublicAseguradosPdfSplitRoute
  '/api/public/asegurados/zip': typeof ApiPublicAseguradosZipRoute
  '/_admin/cliente/$clienteId/poliza/$polizaId': typeof AdminClienteClienteIdPolizaPolizaIdRoute
  '/_admin/empresa/$empresaId/empleado/$empleadoId': typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aseguradoras'
    | '/cartera'
    | '/dashboard'
    | '/mi-perfil'
    | '/mis-documentos'
    | '/mis-pagos'
    | '/mis-polizas'
    | '/documentos'
    | '/empleados'
    | '/movimientos'
    | '/pagos'
    | '/perfil'
    | '/seguros'
    | '/aseguradora/$aseguradoraId'
    | '/cliente/$clienteId'
    | '/empresa/nueva'
    | '/consentimiento/ver'
    | '/empleado/$empleadoId'
    | '/seguros/$polizaId'
    | '/empresa/poliza/$polizaId'
    | '/empresa/poliza/nueva'
    | '/api/public/asegurados/pdf-split'
    | '/api/public/asegurados/zip'
    | '/cliente/$clienteId/poliza/$polizaId'
    | '/empresa/$empresaId/empleado/$empleadoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/aseguradoras'
    | '/cartera'
    | '/dashboard'
    | '/mi-perfil'
    | '/mis-documentos'
    | '/mis-pagos'
    | '/mis-polizas'
    | '/documentos'
    | '/empleados'
    | '/movimientos'
    | '/pagos'
    | '/perfil'
    | '/seguros'
    | '/aseguradora/$aseguradoraId'
    | '/cliente/$clienteId'
    | '/empresa/nueva'
    | '/consentimiento/ver'
    | '/empleado/$empleadoId'
    | '/seguros/$polizaId'
    | '/empresa/poliza/$polizaId'
    | '/empresa/poliza/nueva'
    | '/api/public/asegurados/pdf-split'
    | '/api/public/asegurados/zip'
    | '/cliente/$clienteId/poliza/$polizaId'
    | '/empresa/$empresaId/empleado/$empleadoId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_client'
    | '/_company'
    | '/login'
    | '/_admin/aseguradoras'
    | '/_admin/cartera'
    | '/_admin/dashboard'
    | '/_client/mi-perfil'
    | '/_client/mis-documentos'
    | '/_client/mis-pagos'
    | '/_client/mis-polizas'
    | '/_company/documentos'
    | '/_company/empleados'
    | '/_company/movimientos'
    | '/_company/pagos'
    | '/_company/perfil'
    | '/_company/seguros'
    | '/_admin/aseguradora/$aseguradoraId'
    | '/_admin/cliente/$clienteId'
    | '/_admin/empresa/nueva'
    | '/_client/consentimiento/ver'
    | '/_company/empleado/$empleadoId'
    | '/_company/seguros/$polizaId'
    | '/_admin/empresa/poliza/$polizaId'
    | '/_admin/empresa/poliza/nueva'
    | '/api/public/asegurados/pdf-split'
    | '/api/public/asegurados/zip'
    | '/_admin/cliente/$clienteId/poliza/$polizaId'
    | '/_admin/empresa/$empresaId/empleado/$empleadoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAseguradosPdfSplitRoute: typeof ApiPublicAseguradosPdfSplitRoute
  ApiPublicAseguradosZipRoute: typeof ApiPublicAseguradosZipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_company': {
      id: '/_company'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_company/seguros': {
      id: '/_company/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof CompanySegurosRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/perfil': {
      id: '/_company/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof CompanyPerfilRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/pagos': {
      id: '/_company/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof CompanyPagosRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/movimientos': {
      id: '/_company/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof CompanyMovimientosRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/empleados': {
      id: '/_company/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof CompanyEmpleadosRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/documentos': {
      id: '/_company/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof CompanyDocumentosRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_client/mis-polizas': {
      id: '/_client/mis-polizas'
      path: '/mis-polizas'
      fullPath: '/mis-polizas'
      preLoaderRoute: typeof ClientMisPolizasRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/mis-pagos': {
      id: '/_client/mis-pagos'
      path: '/mis-pagos'
      fullPath: '/mis-pagos'
      preLoaderRoute: typeof ClientMisPagosRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/mis-documentos': {
      id: '/_client/mis-documentos'
      path: '/mis-documentos'
      fullPath: '/mis-documentos'
      preLoaderRoute: typeof ClientMisDocumentosRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/mi-perfil': {
      id: '/_client/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof ClientMiPerfilRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cartera': {
      id: '/_admin/cartera'
      path: '/cartera'
      fullPath: '/cartera'
      preLoaderRoute: typeof AdminCarteraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/aseguradoras': {
      id: '/_admin/aseguradoras'
      path: '/aseguradoras'
      fullPath: '/aseguradoras'
      preLoaderRoute: typeof AdminAseguradorasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_company/seguros/$polizaId': {
      id: '/_company/seguros/$polizaId'
      path: '/$polizaId'
      fullPath: '/seguros/$polizaId'
      preLoaderRoute: typeof CompanySegurosPolizaIdRouteImport
      parentRoute: typeof CompanySegurosRoute
    }
    '/_company/empleado/$empleadoId': {
      id: '/_company/empleado/$empleadoId'
      path: '/empleado/$empleadoId'
      fullPath: '/empleado/$empleadoId'
      preLoaderRoute: typeof CompanyEmpleadoEmpleadoIdRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_client/consentimiento/ver': {
      id: '/_client/consentimiento/ver'
      path: '/consentimiento/ver'
      fullPath: '/consentimiento/ver'
      preLoaderRoute: typeof ClientConsentimientoVerRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_admin/empresa/nueva': {
      id: '/_admin/empresa/nueva'
      path: '/empresa/nueva'
      fullPath: '/empresa/nueva'
      preLoaderRoute: typeof AdminEmpresaNuevaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cliente/$clienteId': {
      id: '/_admin/cliente/$clienteId'
      path: '/cliente/$clienteId'
      fullPath: '/cliente/$clienteId'
      preLoaderRoute: typeof AdminClienteClienteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/aseguradora/$aseguradoraId': {
      id: '/_admin/aseguradora/$aseguradoraId'
      path: '/aseguradora/$aseguradoraId'
      fullPath: '/aseguradora/$aseguradoraId'
      preLoaderRoute: typeof AdminAseguradoraAseguradoraIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/asegurados/zip': {
      id: '/api/public/asegurados/zip'
      path: '/api/public/asegurados/zip'
      fullPath: '/api/public/asegurados/zip'
      preLoaderRoute: typeof ApiPublicAseguradosZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asegurados/pdf-split': {
      id: '/api/public/asegurados/pdf-split'
      path: '/api/public/asegurados/pdf-split'
      fullPath: '/api/public/asegurados/pdf-split'
      preLoaderRoute: typeof ApiPublicAseguradosPdfSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/empresa/poliza/nueva': {
      id: '/_admin/empresa/poliza/nueva'
      path: '/empresa/poliza/nueva'
      fullPath: '/empresa/poliza/nueva'
      preLoaderRoute: typeof AdminEmpresaPolizaNuevaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresa/poliza/$polizaId': {
      id: '/_admin/empresa/poliza/$polizaId'
      path: '/empresa/poliza/$polizaId'
      fullPath: '/empresa/poliza/$polizaId'
      preLoaderRoute: typeof AdminEmpresaPolizaPolizaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresa/$empresaId/empleado/$empleadoId': {
      id: '/_admin/empresa/$empresaId/empleado/$empleadoId'
      path: '/empresa/$empresaId/empleado/$empleadoId'
      fullPath: '/empresa/$empresaId/empleado/$empleadoId'
      preLoaderRoute: typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cliente/$clienteId/poliza/$polizaId': {
      id: '/_admin/cliente/$clienteId/poliza/$polizaId'
      path: '/poliza/$polizaId'
      fullPath: '/cliente/$clienteId/poliza/$polizaId'
      preLoaderRoute: typeof AdminClienteClienteIdPolizaPolizaIdRouteImport
      parentRoute: typeof AdminClienteClienteIdRoute
    }
  }
}

interface AdminClienteClienteIdRouteChildren {
  AdminClienteClienteIdPolizaPolizaIdRoute: typeof AdminClienteClienteIdPolizaPolizaIdRoute
}

const AdminClienteClienteIdRouteChildren: AdminClienteClienteIdRouteChildren = {
  AdminClienteClienteIdPolizaPolizaIdRoute:
    AdminClienteClienteIdPolizaPolizaIdRoute,
}

const AdminClienteClienteIdRouteWithChildren =
  AdminClienteClienteIdRoute._addFileChildren(
    AdminClienteClienteIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminAseguradorasRoute: typeof AdminAseguradorasRoute
  AdminCarteraRoute: typeof AdminCarteraRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminAseguradoraAseguradoraIdRoute: typeof AdminAseguradoraAseguradoraIdRoute
  AdminClienteClienteIdRoute: typeof AdminClienteClienteIdRouteWithChildren
  AdminEmpresaNuevaRoute: typeof AdminEmpresaNuevaRoute
  AdminEmpresaPolizaPolizaIdRoute: typeof AdminEmpresaPolizaPolizaIdRoute
  AdminEmpresaPolizaNuevaRoute: typeof AdminEmpresaPolizaNuevaRoute
  AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute: typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAseguradorasRoute: AdminAseguradorasRoute,
  AdminCarteraRoute: AdminCarteraRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminAseguradoraAseguradoraIdRoute: AdminAseguradoraAseguradoraIdRoute,
  AdminClienteClienteIdRoute: AdminClienteClienteIdRouteWithChildren,
  AdminEmpresaNuevaRoute: AdminEmpresaNuevaRoute,
  AdminEmpresaPolizaPolizaIdRoute: AdminEmpresaPolizaPolizaIdRoute,
  AdminEmpresaPolizaNuevaRoute: AdminEmpresaPolizaNuevaRoute,
  AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute:
    AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientMiPerfilRoute: typeof ClientMiPerfilRoute
  ClientMisDocumentosRoute: typeof ClientMisDocumentosRoute
  ClientMisPagosRoute: typeof ClientMisPagosRoute
  ClientMisPolizasRoute: typeof ClientMisPolizasRoute
  ClientConsentimientoVerRoute: typeof ClientConsentimientoVerRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientMiPerfilRoute: ClientMiPerfilRoute,
  ClientMisDocumentosRoute: ClientMisDocumentosRoute,
  ClientMisPagosRoute: ClientMisPagosRoute,
  ClientMisPolizasRoute: ClientMisPolizasRoute,
  ClientConsentimientoVerRoute: ClientConsentimientoVerRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface CompanySegurosRouteChildren {
  CompanySegurosPolizaIdRoute: typeof CompanySegurosPolizaIdRoute
}

const CompanySegurosRouteChildren: CompanySegurosRouteChildren = {
  CompanySegurosPolizaIdRoute: CompanySegurosPolizaIdRoute,
}

const CompanySegurosRouteWithChildren = CompanySegurosRoute._addFileChildren(
  CompanySegurosRouteChildren,
)

interface CompanyRouteChildren {
  CompanyDocumentosRoute: typeof CompanyDocumentosRoute
  CompanyEmpleadosRoute: typeof CompanyEmpleadosRoute
  CompanyMovimientosRoute: typeof CompanyMovimientosRoute
  CompanyPagosRoute: typeof CompanyPagosRoute
  CompanyPerfilRoute: typeof CompanyPerfilRoute
  CompanySegurosRoute: typeof CompanySegurosRouteWithChildren
  CompanyEmpleadoEmpleadoIdRoute: typeof CompanyEmpleadoEmpleadoIdRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyDocumentosRoute: CompanyDocumentosRoute,
  CompanyEmpleadosRoute: CompanyEmpleadosRoute,
  CompanyMovimientosRoute: CompanyMovimientosRoute,
  CompanyPagosRoute: CompanyPagosRoute,
  CompanyPerfilRoute: CompanyPerfilRoute,
  CompanySegurosRoute: CompanySegurosRouteWithChildren,
  CompanyEmpleadoEmpleadoIdRoute: CompanyEmpleadoEmpleadoIdRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAseguradosPdfSplitRoute: ApiPublicAseguradosPdfSplitRoute,
  ApiPublicAseguradosZipRoute: ApiPublicAseguradosZipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
