/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminCuestionarioRouteImport } from './routes/_admin/cuestionario'
import { Route as AdminCotizadoresRouteImport } from './routes/_admin/cotizadores'
import { Route as AdminCarteraRouteImport } from './routes/_admin/cartera'
import { Route as AdminAseguradorasRouteImport } from './routes/_admin/aseguradoras'
import { Route as AdminEmpresaNuevaRouteImport } from './routes/_admin/empresa.nueva'
import { Route as AdminEmpresaPolizaNuevaRouteImport } from './routes/_admin/empresa.poliza.nueva'
import { Route as AdminEmpresaPolizaPolizaIdRouteImport } from './routes/_admin/empresa.poliza.$polizaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuestionarioRoute = AdminCuestionarioRouteImport.update({
  id: '/cuestionario',
  path: '/cuestionario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCotizadoresRoute = AdminCotizadoresRouteImport.update({
  id: '/cotizadores',
  path: '/cotizadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarteraRoute = AdminCarteraRouteImport.update({
  id: '/cartera',
  path: '/cartera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAseguradorasRoute = AdminAseguradorasRouteImport.update({
  id: '/aseguradoras',
  path: '/aseguradoras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresaNuevaRoute = AdminEmpresaNuevaRouteImport.update({
  id: '/empresa/nueva',
  path: '/empresa/nueva',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresaPolizaNuevaRoute = AdminEmpresaPolizaNuevaRouteImport.update({
  id: '/empresa/poliza/nueva',
  path: '/empresa/poliza/nueva',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresaPolizaPolizaIdRoute =
  AdminEmpresaPolizaPolizaIdRouteImport.update({
    id: '/empresa/poliza/$polizaId',
    path: '/empresa/poliza/$polizaId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aseguradoras': typeof AdminAseguradorasRoute
  '/cartera': typeof AdminCarteraRoute
  '/cotizadores': typeof AdminCotizadoresRoute
  '/cuestionario': typeof AdminCuestionarioRoute
  '/dashboard': typeof AdminDashboardRoute
  '/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aseguradoras': typeof AdminAseguradorasRoute
  '/cartera': typeof AdminCarteraRoute
  '/cotizadores': typeof AdminCotizadoresRoute
  '/cuestionario': typeof AdminCuestionarioRoute
  '/dashboard': typeof AdminDashboardRoute
  '/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/aseguradoras': typeof AdminAseguradorasRoute
  '/_admin/cartera': typeof AdminCarteraRoute
  '/_admin/cotizadores': typeof AdminCotizadoresRoute
  '/_admin/cuestionario': typeof AdminCuestionarioRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/_admin/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/_admin/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aseguradoras'
    | '/cartera'
    | '/cotizadores'
    | '/cuestionario'
    | '/dashboard'
    | '/empresa/nueva'
    | '/empresa/poliza/$polizaId'
    | '/empresa/poliza/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/aseguradoras'
    | '/cartera'
    | '/cotizadores'
    | '/cuestionario'
    | '/dashboard'
    | '/empresa/nueva'
    | '/empresa/poliza/$polizaId'
    | '/empresa/poliza/nueva'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/aseguradoras'
    | '/_admin/cartera'
    | '/_admin/cotizadores'
    | '/_admin/cuestionario'
    | '/_admin/dashboard'
    | '/_admin/empresa/nueva'
    | '/_admin/empresa/poliza/$polizaId'
    | '/_admin/empresa/poliza/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cuestionario': {
      id: '/_admin/cuestionario'
      path: '/cuestionario'
      fullPath: '/cuestionario'
      preLoaderRoute: typeof AdminCuestionarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cotizadores': {
      id: '/_admin/cotizadores'
      path: '/cotizadores'
      fullPath: '/cotizadores'
      preLoaderRoute: typeof AdminCotizadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cartera': {
      id: '/_admin/cartera'
      path: '/cartera'
      fullPath: '/cartera'
      preLoaderRoute: typeof AdminCarteraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/aseguradoras': {
      id: '/_admin/aseguradoras'
      path: '/aseguradoras'
      fullPath: '/aseguradoras'
      preLoaderRoute: typeof AdminAseguradorasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresa/nueva': {
      id: '/_admin/empresa/nueva'
      path: '/empresa/nueva'
      fullPath: '/empresa/nueva'
      preLoaderRoute: typeof AdminEmpresaNuevaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresa/poliza/nueva': {
      id: '/_admin/empresa/poliza/nueva'
      path: '/empresa/poliza/nueva'
      fullPath: '/empresa/poliza/nueva'
      preLoaderRoute: typeof AdminEmpresaPolizaNuevaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresa/poliza/$polizaId': {
      id: '/_admin/empresa/poliza/$polizaId'
      path: '/empresa/poliza/$polizaId'
      fullPath: '/empresa/poliza/$polizaId'
      preLoaderRoute: typeof AdminEmpresaPolizaPolizaIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAseguradorasRoute: typeof AdminAseguradorasRoute
  AdminCarteraRoute: typeof AdminCarteraRoute
  AdminCotizadoresRoute: typeof AdminCotizadoresRoute
  AdminCuestionarioRoute: typeof AdminCuestionarioRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmpresaNuevaRoute: typeof AdminEmpresaNuevaRoute
  AdminEmpresaPolizaPolizaIdRoute: typeof AdminEmpresaPolizaPolizaIdRoute
  AdminEmpresaPolizaNuevaRoute: typeof AdminEmpresaPolizaNuevaRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAseguradorasRoute: AdminAseguradorasRoute,
  AdminCarteraRoute: AdminCarteraRoute,
  AdminCotizadoresRoute: AdminCotizadoresRoute,
  AdminCuestionarioRoute: AdminCuestionarioRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmpresaNuevaRoute: AdminEmpresaNuevaRoute,
  AdminEmpresaPolizaPolizaIdRoute: AdminEmpresaPolizaPolizaIdRoute,
  AdminEmpresaPolizaNuevaRoute: AdminEmpresaPolizaNuevaRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
