/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompanyRouteImport } from './routes/_company'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySegurosRouteImport } from './routes/_company/seguros'
import { Route as CompanyPerfilRouteImport } from './routes/_company/perfil'
import { Route as CompanyPagosRouteImport } from './routes/_company/pagos'
import { Route as CompanyEmpleadosRouteImport } from './routes/_company/empleados'
import { Route as ClientMisPolizasRouteImport } from './routes/_client/mis-polizas'
import { Route as ClientMisPagosRouteImport } from './routes/_client/mis-pagos'
import { Route as ClientMiPerfilRouteImport } from './routes/_client/mi-perfil'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminCuestionarioRouteImport } from './routes/_admin/cuestionario'
import { Route as AdminCotizadoresRouteImport } from './routes/_admin/cotizadores'
import { Route as AdminCarteraRouteImport } from './routes/_admin/cartera'
import { Route as AdminAseguradorasRouteImport } from './routes/_admin/aseguradoras'
import { Route as CompanySegurosPolizaIdRouteImport } from './routes/_company/seguros.$polizaId'
import { Route as AdminEmpresaNuevaRouteImport } from './routes/_admin/empresa.nueva'
import { Route as AdminClienteClienteIdRouteImport } from './routes/_admin/cliente.$clienteId'
import { Route as AdminEmpresaPolizaNuevaRouteImport } from './routes/_admin/empresa.poliza.nueva'
import { Route as AdminEmpresaPolizaPolizaIdRouteImport } from './routes/_admin/empresa.poliza.$polizaId'
import { Route as AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRouteImport } from './routes/_admin/empresa.$empresaId.empleado.$empleadoId'
import { Route as AdminClienteClienteIdPolizaPolizaIdRouteImport } from './routes/_admin/cliente.$clienteId.poliza.$polizaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/_company',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySegurosRoute = CompanySegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyPerfilRoute = CompanyPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyPagosRoute = CompanyPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyEmpleadosRoute = CompanyEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => CompanyRoute,
} as any)
const ClientMisPolizasRoute = ClientMisPolizasRouteImport.update({
  id: '/mis-polizas',
  path: '/mis-polizas',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMisPagosRoute = ClientMisPagosRouteImport.update({
  id: '/mis-pagos',
  path: '/mis-pagos',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMiPerfilRoute = ClientMiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => ClientRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuestionarioRoute = AdminCuestionarioRouteImport.update({
  id: '/cuestionario',
  path: '/cuestionario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCotizadoresRoute = AdminCotizadoresRouteImport.update({
  id: '/cotizadores',
  path: '/cotizadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarteraRoute = AdminCarteraRouteImport.update({
  id: '/cartera',
  path: '/cartera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAseguradorasRoute = AdminAseguradorasRouteImport.update({
  id: '/aseguradoras',
  path: '/aseguradoras',
  getParentRoute: () => AdminRoute,
} as any)
const CompanySegurosPolizaIdRoute = CompanySegurosPolizaIdRouteImport.update({
  id: '/$polizaId',
  path: '/$polizaId',
  getParentRoute: () => CompanySegurosRoute,
} as any)
const AdminEmpresaNuevaRoute = AdminEmpresaNuevaRouteImport.update({
  id: '/empresa/nueva',
  path: '/empresa/nueva',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClienteClienteIdRoute = AdminClienteClienteIdRouteImport.update({
  id: '/cliente/$clienteId',
  path: '/cliente/$clienteId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresaPolizaNuevaRoute = AdminEmpresaPolizaNuevaRouteImport.update({
  id: '/empresa/poliza/nueva',
  path: '/empresa/poliza/nueva',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresaPolizaPolizaIdRoute =
  AdminEmpresaPolizaPolizaIdRouteImport.update({
    id: '/empresa/poliza/$polizaId',
    path: '/empresa/poliza/$polizaId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute =
  AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRouteImport.update({
    id: '/empresa/$empresaId/empleado/$empleadoId',
    path: '/empresa/$empresaId/empleado/$empleadoId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClienteClienteIdPolizaPolizaIdRoute =
  AdminClienteClienteIdPolizaPolizaIdRouteImport.update({
    id: '/poliza/$polizaId',
    path: '/poliza/$polizaId',
    getParentRoute: () => AdminClienteClienteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aseguradoras': typeof AdminAseguradorasRoute
  '/cartera': typeof AdminCarteraRoute
  '/cotizadores': typeof AdminCotizadoresRoute
  '/cuestionario': typeof AdminCuestionarioRoute
  '/dashboard': typeof AdminDashboardRoute
  '/mi-perfil': typeof ClientMiPerfilRoute
  '/mis-pagos': typeof ClientMisPagosRoute
  '/mis-polizas': typeof ClientMisPolizasRoute
  '/empleados': typeof CompanyEmpleadosRoute
  '/pagos': typeof CompanyPagosRoute
  '/perfil': typeof CompanyPerfilRoute
  '/seguros': typeof CompanySegurosRouteWithChildren
  '/cliente/$clienteId': typeof AdminClienteClienteIdRouteWithChildren
  '/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/seguros/$polizaId': typeof CompanySegurosPolizaIdRoute
  '/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
  '/cliente/$clienteId/poliza/$polizaId': typeof AdminClienteClienteIdPolizaPolizaIdRoute
  '/empresa/$empresaId/empleado/$empleadoId': typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aseguradoras': typeof AdminAseguradorasRoute
  '/cartera': typeof AdminCarteraRoute
  '/cotizadores': typeof AdminCotizadoresRoute
  '/cuestionario': typeof AdminCuestionarioRoute
  '/dashboard': typeof AdminDashboardRoute
  '/mi-perfil': typeof ClientMiPerfilRoute
  '/mis-pagos': typeof ClientMisPagosRoute
  '/mis-polizas': typeof ClientMisPolizasRoute
  '/empleados': typeof CompanyEmpleadosRoute
  '/pagos': typeof CompanyPagosRoute
  '/perfil': typeof CompanyPerfilRoute
  '/seguros': typeof CompanySegurosRouteWithChildren
  '/cliente/$clienteId': typeof AdminClienteClienteIdRouteWithChildren
  '/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/seguros/$polizaId': typeof CompanySegurosPolizaIdRoute
  '/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
  '/cliente/$clienteId/poliza/$polizaId': typeof AdminClienteClienteIdPolizaPolizaIdRoute
  '/empresa/$empresaId/empleado/$empleadoId': typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_client': typeof ClientRouteWithChildren
  '/_company': typeof CompanyRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/aseguradoras': typeof AdminAseguradorasRoute
  '/_admin/cartera': typeof AdminCarteraRoute
  '/_admin/cotizadores': typeof AdminCotizadoresRoute
  '/_admin/cuestionario': typeof AdminCuestionarioRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_client/mi-perfil': typeof ClientMiPerfilRoute
  '/_client/mis-pagos': typeof ClientMisPagosRoute
  '/_client/mis-polizas': typeof ClientMisPolizasRoute
  '/_company/empleados': typeof CompanyEmpleadosRoute
  '/_company/pagos': typeof CompanyPagosRoute
  '/_company/perfil': typeof CompanyPerfilRoute
  '/_company/seguros': typeof CompanySegurosRouteWithChildren
  '/_admin/cliente/$clienteId': typeof AdminClienteClienteIdRouteWithChildren
  '/_admin/empresa/nueva': typeof AdminEmpresaNuevaRoute
  '/_company/seguros/$polizaId': typeof CompanySegurosPolizaIdRoute
  '/_admin/empresa/poliza/$polizaId': typeof AdminEmpresaPolizaPolizaIdRoute
  '/_admin/empresa/poliza/nueva': typeof AdminEmpresaPolizaNuevaRoute
  '/_admin/cliente/$clienteId/poliza/$polizaId': typeof AdminClienteClienteIdPolizaPolizaIdRoute
  '/_admin/empresa/$empresaId/empleado/$empleadoId': typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aseguradoras'
    | '/cartera'
    | '/cotizadores'
    | '/cuestionario'
    | '/dashboard'
    | '/mi-perfil'
    | '/mis-pagos'
    | '/mis-polizas'
    | '/empleados'
    | '/pagos'
    | '/perfil'
    | '/seguros'
    | '/cliente/$clienteId'
    | '/empresa/nueva'
    | '/seguros/$polizaId'
    | '/empresa/poliza/$polizaId'
    | '/empresa/poliza/nueva'
    | '/cliente/$clienteId/poliza/$polizaId'
    | '/empresa/$empresaId/empleado/$empleadoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/aseguradoras'
    | '/cartera'
    | '/cotizadores'
    | '/cuestionario'
    | '/dashboard'
    | '/mi-perfil'
    | '/mis-pagos'
    | '/mis-polizas'
    | '/empleados'
    | '/pagos'
    | '/perfil'
    | '/seguros'
    | '/cliente/$clienteId'
    | '/empresa/nueva'
    | '/seguros/$polizaId'
    | '/empresa/poliza/$polizaId'
    | '/empresa/poliza/nueva'
    | '/cliente/$clienteId/poliza/$polizaId'
    | '/empresa/$empresaId/empleado/$empleadoId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_client'
    | '/_company'
    | '/login'
    | '/_admin/aseguradoras'
    | '/_admin/cartera'
    | '/_admin/cotizadores'
    | '/_admin/cuestionario'
    | '/_admin/dashboard'
    | '/_client/mi-perfil'
    | '/_client/mis-pagos'
    | '/_client/mis-polizas'
    | '/_company/empleados'
    | '/_company/pagos'
    | '/_company/perfil'
    | '/_company/seguros'
    | '/_admin/cliente/$clienteId'
    | '/_admin/empresa/nueva'
    | '/_company/seguros/$polizaId'
    | '/_admin/empresa/poliza/$polizaId'
    | '/_admin/empresa/poliza/nueva'
    | '/_admin/cliente/$clienteId/poliza/$polizaId'
    | '/_admin/empresa/$empresaId/empleado/$empleadoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_company': {
      id: '/_company'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_company/seguros': {
      id: '/_company/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof CompanySegurosRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/perfil': {
      id: '/_company/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof CompanyPerfilRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/pagos': {
      id: '/_company/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof CompanyPagosRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/empleados': {
      id: '/_company/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof CompanyEmpleadosRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_client/mis-polizas': {
      id: '/_client/mis-polizas'
      path: '/mis-polizas'
      fullPath: '/mis-polizas'
      preLoaderRoute: typeof ClientMisPolizasRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/mis-pagos': {
      id: '/_client/mis-pagos'
      path: '/mis-pagos'
      fullPath: '/mis-pagos'
      preLoaderRoute: typeof ClientMisPagosRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/mi-perfil': {
      id: '/_client/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof ClientMiPerfilRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cuestionario': {
      id: '/_admin/cuestionario'
      path: '/cuestionario'
      fullPath: '/cuestionario'
      preLoaderRoute: typeof AdminCuestionarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cotizadores': {
      id: '/_admin/cotizadores'
      path: '/cotizadores'
      fullPath: '/cotizadores'
      preLoaderRoute: typeof AdminCotizadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cartera': {
      id: '/_admin/cartera'
      path: '/cartera'
      fullPath: '/cartera'
      preLoaderRoute: typeof AdminCarteraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/aseguradoras': {
      id: '/_admin/aseguradoras'
      path: '/aseguradoras'
      fullPath: '/aseguradoras'
      preLoaderRoute: typeof AdminAseguradorasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_company/seguros/$polizaId': {
      id: '/_company/seguros/$polizaId'
      path: '/$polizaId'
      fullPath: '/seguros/$polizaId'
      preLoaderRoute: typeof CompanySegurosPolizaIdRouteImport
      parentRoute: typeof CompanySegurosRoute
    }
    '/_admin/empresa/nueva': {
      id: '/_admin/empresa/nueva'
      path: '/empresa/nueva'
      fullPath: '/empresa/nueva'
      preLoaderRoute: typeof AdminEmpresaNuevaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cliente/$clienteId': {
      id: '/_admin/cliente/$clienteId'
      path: '/cliente/$clienteId'
      fullPath: '/cliente/$clienteId'
      preLoaderRoute: typeof AdminClienteClienteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresa/poliza/nueva': {
      id: '/_admin/empresa/poliza/nueva'
      path: '/empresa/poliza/nueva'
      fullPath: '/empresa/poliza/nueva'
      preLoaderRoute: typeof AdminEmpresaPolizaNuevaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresa/poliza/$polizaId': {
      id: '/_admin/empresa/poliza/$polizaId'
      path: '/empresa/poliza/$polizaId'
      fullPath: '/empresa/poliza/$polizaId'
      preLoaderRoute: typeof AdminEmpresaPolizaPolizaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresa/$empresaId/empleado/$empleadoId': {
      id: '/_admin/empresa/$empresaId/empleado/$empleadoId'
      path: '/empresa/$empresaId/empleado/$empleadoId'
      fullPath: '/empresa/$empresaId/empleado/$empleadoId'
      preLoaderRoute: typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cliente/$clienteId/poliza/$polizaId': {
      id: '/_admin/cliente/$clienteId/poliza/$polizaId'
      path: '/poliza/$polizaId'
      fullPath: '/cliente/$clienteId/poliza/$polizaId'
      preLoaderRoute: typeof AdminClienteClienteIdPolizaPolizaIdRouteImport
      parentRoute: typeof AdminClienteClienteIdRoute
    }
  }
}

interface AdminClienteClienteIdRouteChildren {
  AdminClienteClienteIdPolizaPolizaIdRoute: typeof AdminClienteClienteIdPolizaPolizaIdRoute
}

const AdminClienteClienteIdRouteChildren: AdminClienteClienteIdRouteChildren = {
  AdminClienteClienteIdPolizaPolizaIdRoute:
    AdminClienteClienteIdPolizaPolizaIdRoute,
}

const AdminClienteClienteIdRouteWithChildren =
  AdminClienteClienteIdRoute._addFileChildren(
    AdminClienteClienteIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminAseguradorasRoute: typeof AdminAseguradorasRoute
  AdminCarteraRoute: typeof AdminCarteraRoute
  AdminCotizadoresRoute: typeof AdminCotizadoresRoute
  AdminCuestionarioRoute: typeof AdminCuestionarioRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminClienteClienteIdRoute: typeof AdminClienteClienteIdRouteWithChildren
  AdminEmpresaNuevaRoute: typeof AdminEmpresaNuevaRoute
  AdminEmpresaPolizaPolizaIdRoute: typeof AdminEmpresaPolizaPolizaIdRoute
  AdminEmpresaPolizaNuevaRoute: typeof AdminEmpresaPolizaNuevaRoute
  AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute: typeof AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAseguradorasRoute: AdminAseguradorasRoute,
  AdminCarteraRoute: AdminCarteraRoute,
  AdminCotizadoresRoute: AdminCotizadoresRoute,
  AdminCuestionarioRoute: AdminCuestionarioRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminClienteClienteIdRoute: AdminClienteClienteIdRouteWithChildren,
  AdminEmpresaNuevaRoute: AdminEmpresaNuevaRoute,
  AdminEmpresaPolizaPolizaIdRoute: AdminEmpresaPolizaPolizaIdRoute,
  AdminEmpresaPolizaNuevaRoute: AdminEmpresaPolizaNuevaRoute,
  AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute:
    AdminEmpresaEmpresaIdEmpleadoEmpleadoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientMiPerfilRoute: typeof ClientMiPerfilRoute
  ClientMisPagosRoute: typeof ClientMisPagosRoute
  ClientMisPolizasRoute: typeof ClientMisPolizasRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientMiPerfilRoute: ClientMiPerfilRoute,
  ClientMisPagosRoute: ClientMisPagosRoute,
  ClientMisPolizasRoute: ClientMisPolizasRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface CompanySegurosRouteChildren {
  CompanySegurosPolizaIdRoute: typeof CompanySegurosPolizaIdRoute
}

const CompanySegurosRouteChildren: CompanySegurosRouteChildren = {
  CompanySegurosPolizaIdRoute: CompanySegurosPolizaIdRoute,
}

const CompanySegurosRouteWithChildren = CompanySegurosRoute._addFileChildren(
  CompanySegurosRouteChildren,
)

interface CompanyRouteChildren {
  CompanyEmpleadosRoute: typeof CompanyEmpleadosRoute
  CompanyPagosRoute: typeof CompanyPagosRoute
  CompanyPerfilRoute: typeof CompanyPerfilRoute
  CompanySegurosRoute: typeof CompanySegurosRouteWithChildren
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyEmpleadosRoute: CompanyEmpleadosRoute,
  CompanyPagosRoute: CompanyPagosRoute,
  CompanyPerfilRoute: CompanyPerfilRoute,
  CompanySegurosRoute: CompanySegurosRouteWithChildren,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
